version: 0.1

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"   # 3.10–3.12 are also fine

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt

formats: all   # optional: htmlzip/pdf/epub